[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# If you have an SWD debugfer, you can uncomment this line:
runner = "probe-rs run --chip RP235x --speed 12000 --protocol swd"

# If you don't, you can put the pico into the USB loader, and use this
# line instead:
# runner = "picotool load -x -t elf"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
